/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useEffect, useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { a } from "@react-spring/three";
import islandScene from "../assets/3d/island3.glb";
import { useFrame, useThree } from "@react-three/fiber";

const Island = ({ isRotating, setIsRotating, setCurrentStage, setRotationSpeed, islandRotation, ...props }) => {
  const islandRef = useRef();

  const { gl, viewport } = useThree();
  const { nodes, materials } = useGLTF(islandScene);

  const lastX = useRef(0);
  const rotationSpeed = useRef(0);
  const dampingFactor = 0.95;

  const handlePointerDown = (e) => {
    e.stopPropagation();
    e.preventDefault();
    setIsRotating(true);

    const clientX = e.touches
      ? e.touches[0].clientX
      : e.clientX;

    lastX.current = clientX;
  }

  const handlePointerUp = (e) => {
    e.stopPropagation();
    e.preventDefault();
    setIsRotating(false);
  }

  const handlePointerMove = (e) => {
    e.stopPropagation();
    e.preventDefault();

    if (isRotating) {
      const clientX = e.touches
        ? e.touches[0].clientX
        : e.clientX;

      const delta = (clientX - lastX.current) / viewport.width;

      islandRef.current.rotation.y += delta * Math.PI * 0.01;
      lastX.current = clientX;
      rotationSpeed.current = delta * 0.01 * Math.PI;
    }
  }

  const handleKeyDown = (e) => {
    if (e.key === "ArrowLeft") {
      if (!isRotating) setIsRotating(true);
      islandRef.current.rotation.y += 0.01 * Math.PI;
      rotationSpeed.current = 0.001 * Math.PI; // Update speed
    } else if (e.key === "ArrowRight") {
      if (!isRotating) setIsRotating(true);
      islandRef.current.rotation.y -= 0.01 * Math.PI;
      rotationSpeed.current = -0.001 * Math.PI; // Update speed
    }
  }

  const handleKeyUp = (e) => {
    if (e.key === "ArrowLeft" || e.key === "ArrowRight") {
      setIsRotating(false);
      rotationSpeed.current = 0; // Reset speed after release
    }
  }

  useFrame(() => {
    if (!isRotating) {
      rotationSpeed.current *= dampingFactor;

      if (Math.abs(rotationSpeed.current) < 0.0001) {
        rotationSpeed.current = 0;
      }

      islandRef.current.rotation.y += rotationSpeed.current;
    } else {
      const rotation = islandRef.current.rotation.y;

      const normalizedRotation = ((rotation % (2 * Math.PI)) + 2 * Math.PI) % (2 * Math.PI);

      // Set the current stage based on the island's orientation
      switch (true) {
        case normalizedRotation >= 3.1 && normalizedRotation <= 3.4:
          setCurrentStage(1);
          break;
        case normalizedRotation >= 3.8 && normalizedRotation <= 4.1:
          setCurrentStage(9);
          break;
        case normalizedRotation >= 4.5 && normalizedRotation <= 4.8:
          setCurrentStage(8);
          break;
        case normalizedRotation >= 5.2 && normalizedRotation <= 5.5:
          setCurrentStage(7);
          break;
        case normalizedRotation >= 5.9 && normalizedRotation <= 6.2:
          setCurrentStage(6);
          break;
        case normalizedRotation >= 0.6 && normalizedRotation <= 0.9:
          setCurrentStage(5);
          break;
        case normalizedRotation >= 1.3 && normalizedRotation <= 1.6:
          setCurrentStage(4);
          break;
        case normalizedRotation >= 2.0 && normalizedRotation <= 2.3:
          setCurrentStage(3);
          break;
        case normalizedRotation >= 2.7 && normalizedRotation <= 3.0:
          setCurrentStage(2);
          break;
        default:
          setCurrentStage(null);
      }
    }

    setRotationSpeed(rotationSpeed.current);
  })

  useEffect(() => {
    const canvas = gl.domElement;
    canvas.addEventListener("pointerdown", handlePointerDown);
    canvas.addEventListener("pointerup", handlePointerUp);
    canvas.addEventListener("pointermove", handlePointerMove);
    document.addEventListener("keydown", handleKeyDown);
    document.addEventListener("keyup", handleKeyUp);

    return () => {
      canvas.removeEventListener("pointerdown", handlePointerDown);
      canvas.removeEventListener("pointerup", handlePointerUp);
      canvas.removeEventListener("pointermove", handlePointerMove);
      document.removeEventListener("keydown", handleKeyDown);
      document.removeEventListener("keyup", handleKeyUp);
    }
  }, [gl, handlePointerDown, handlePointerUp, handlePointerMove]);

  useEffect(() => {
    if (!currentAnimation || !actions) return;
  
    Object.values(actions).forEach((action) => action.stop());
  
    if (actions[currentAnimation]) {
      actions[currentAnimation].reset().fadeIn(0.5).play();
    }
  }, [actions, currentAnimation]);
  

  /*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

  return (
    <a.group ref={islandRef} {...props}>
      <mesh

        receiveShadow
        geometry={nodes.Circle001.geometry}
        material={materials['Material.014']}
        position={[0, 0.006, 0]}
        scale={[3.9, 4.682, 3.9]}
      />
      <group position={[-2.083, 0.814, 1.806]} rotation={[Math.PI, -0.727, Math.PI]} scale={0.055}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Sphere001.geometry}
          material={materials['FirstTexture.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Sphere001_1.geometry}
          material={materials['Material.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Sphere001_2.geometry}
          material={materials['material_0.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Sphere001_3.geometry}
          material={materials['Material.004']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Sphere001_4.geometry}
          material={materials['Material.017']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Sphere001_5.geometry}
          material={materials['Material.085']}
        />
      </group>
      <mesh

        receiveShadow
        geometry={nodes.Plane.geometry}
        material={materials['Material.015']}
        position={[0, 0.055, 0]}
        scale={4.618}
      />

      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle002.geometry}
        material={materials['Material.016']}
        position={[0, 0.324, 0]}
        scale={3.879}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cone.geometry}
        material={materials['Material.019']}
        position={[0.036, 1.106, 1.094]}
        rotation={[-1.449, 1.355, 1.436]}
        scale={[0.083, 0.11, 0.083]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cone001.geometry}
        material={materials['Material.019']}
        position={[0.192, 1.105, 1.145]}
        rotation={[-2.806, 1.229, 2.968]}
        scale={[0.06, 0.079, 0.06]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cone002.geometry}
        material={materials['Material.019']}
        position={[0.069, 1.115, 1.245]}
        rotation={[-2.501, 1.158, 2.614]}
        scale={[0.046, 0.061, 0.046]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane003.geometry}
        material={nodes.Plane003.material}
        position={[-0.654, 2.237, -0.533]}
        rotation={[0, -0.141, 0]}
        scale={0.134}
      />
      <group position={[0.579, 2.228, -0.527]} rotation={[Math.PI / 2, 0, -1.809]} scale={0.041}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane010.geometry}
          material={materials['Material.004']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane010_1.geometry}
          material={materials['Material.003']}
        />
      </group>
      <group position={[0.002, 2.228, -0.421]} rotation={[Math.PI / 2, 0, -1.575]} scale={0.041}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane009.geometry}
          material={materials['Material.004']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane009_1.geometry}
          material={materials['Material.003']}
        />
      </group>
      <group position={[-0.585, 2.228, -0.442]} rotation={[Math.PI / 2, 0, -1.358]} scale={0.041}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane007.geometry}
          material={materials['Material.004']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane007_1.geometry}
          material={materials['Material.003']}
        />
      </group>
      <group position={[-0.585, 2.228, -0.442]} rotation={[Math.PI / 2, 0, -1.358]} scale={0.041}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane020.geometry}
          material={materials['Material.004']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane020_1.geometry}
          material={materials['Material.003']}
        />
      </group>
      <group position={[2.428, 1.763, 1.457]} rotation={[0.026, 0.915, -0.009]} scale={0.058}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane017.geometry}
          material={materials['Material.002']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane017_1.geometry}
          material={materials.Windows}
        />
      </group>
      <group
        position={[2.427, 1.604, 1.454]}
        rotation={[0.026, 0.915, -0.009]}
        scale={[0.166, 0.163, 0.166]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane015.geometry}
          material={materials['Material.002']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane015_1.geometry}
          material={materials.Windows}
        />
      </group>
      <group
        position={[2.426, 1.446, 1.451]}
        rotation={[0.026, 0.915, -0.009]}
        scale={[0.166, 0.163, 0.166]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane014.geometry}
          material={materials['Material.002']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane014_1.geometry}
          material={materials.Windows}
        />
      </group>
      <group
        position={[2.425, 1.287, 1.448]}
        rotation={[0.026, 0.915, -0.009]}
        scale={[0.165, 0.163, 0.165]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane013.geometry}
          material={materials['Material.002']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane013_1.geometry}
          material={materials.Windows}
        />
      </group>
      <group
        position={[2.424, 1.128, 1.445]}
        rotation={[0.026, 0.915, -0.009]}
        scale={[0.164, 0.163, 0.164]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane012.geometry}
          material={materials['Material.002']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane012_1.geometry}
          material={materials.Windows}
        />
      </group>
      <group position={[2.423, 0.969, 1.442]} rotation={[0.026, 0.915, -0.009]} scale={0.163}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane011.geometry}
          material={materials['Material.002']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane011_1.geometry}
          material={materials.Windows}
        />
      </group>
      <group position={[2.422, 0.81, 1.439]} rotation={[0.026, 0.915, -0.009]} scale={0.163}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane002_1.geometry}
          material={materials['Material.002']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane002_2.geometry}
          material={materials.Windows}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Base.geometry}
        material={materials['Pavillon-M.001']}
        position={[2.418, 0.452, 1.431]}
        rotation={[-1.552, 0.006, 0.915]}
        scale={0.295}
      />
      <group position={[2.418, 0.453, 1.431]} rotation={[-1.552, 0.006, 0.915]} scale={0.295}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.BUR_T6_4_PERRONE_01_Material_0013.geometry}
          material={materials['Material.002']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.BUR_T6_4_PERRONE_01_Material_0013_1.geometry}
          material={materials.Windows}
        />
      </group>
      <group position={[2.418, 0.453, 1.431]} rotation={[-1.552, 0.006, 0.915]} scale={0.295}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.BUR_T6_4_PERRONE_01_Material_0012.geometry}
          material={materials['Material.002']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.BUR_T6_4_PERRONE_01_Material_0012_1.geometry}
          material={materials.Metal}
        />
      </group>
      <group position={[2.418, 0.453, 1.431]} rotation={[-1.552, 0.006, 0.915]} scale={0.295}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.BUR_T6_4_PERRONE_01_Material_0002.geometry}
          material={materials['Material.002']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.BUR_T6_4_PERRONE_01_Material_0002_1.geometry}
          material={materials['Material.001']}
        />
      </group>
      <group position={[2.418, 0.452, 1.431]} rotation={[-1.552, 0.006, 0.915]} scale={0.295}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['BUR_T6_4_PERRONE_01001_Pavillon-M001_0001'].geometry}
          material={materials['Pavillon-M.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['BUR_T6_4_PERRONE_01001_Pavillon-M001_0001_1'].geometry}
          material={materials['Material.002']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['BUR_T6_4_PERRONE_01001_Pavillon-M001_0001_2'].geometry}
          material={materials.Windows}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['BUR_T6_4_PERRONE_01001_Pavillon-M001_0001_3'].geometry}
          material={materials.Metal}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['BUR_T6_4_PERRONE_01001_Pavillon-M001_0001_4'].geometry}
          material={materials['Material.001']}
        />
      </group>
      <group position={[-2.004, 0.379, -2.101]} rotation={[-Math.PI / 2, 0, 1.3]} scale={0.034}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_0004.geometry}
          material={materials.School}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_0004_1.geometry}
          material={materials['Material.005']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_0004_2.geometry}
          material={materials['Material.006']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_0004_3.geometry}
          material={materials.Material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_0004_4.geometry}
          material={materials['Material.007']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_0004_5.geometry}
          material={materials.AcademyWindowFrame}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box2.geometry}
        material={materials.AcademyWindowFrame}
        position={[-1.886, 0.385, -2.132]}
        rotation={[-Math.PI / 2, 0, 1.3]}
        scale={0.034}
      />
      <group position={[-1.886, 0.385, -2.132]} rotation={[-Math.PI / 2, 0, 1.3]} scale={0.034}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_01341.geometry}
          material={materials.AcademyWindowFrame}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_01341_1.geometry}
          material={materials['Material.008']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_01341_2.geometry}
          material={materials.Frente}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.CeilingWindow.geometry}
        material={materials.School}
        position={[-1.886, 0.385, -2.132]}
        rotation={[-Math.PI / 2, 0, 1.3]}
        scale={0.034}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Box.geometry}
        material={materials.AcademyWindowFrame}
        position={[-1.886, 0.385, -2.132]}
        rotation={[-Math.PI / 2, 0, 1.3]}
        scale={0.034}
      />
      <group position={[-1.886, 0.385, -2.132]} rotation={[-Math.PI / 2, 0, 1.3]} scale={0.034}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_01264.geometry}
          material={materials.AcademyWindowFrame}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_01264_1.geometry}
          material={materials['Material.008']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_01264_2.geometry}
          material={materials.Frente}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Chimney.geometry}
        material={nodes.Chimney.material}
        position={[-1.677, 0.958, -1.941]}
        rotation={[0, 1.3, 0]}
        scale={0.034}
      />
      <group position={[-1.886, 0.385, -2.132]} rotation={[-Math.PI / 2, 0, 1.3]} scale={0.034}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_01421.geometry}
          material={materials['Material.007']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_01421_1.geometry}
          material={materials.AcademyWindowFrame}
        />
      </group>
      <group position={[-1.886, 0.385, -2.132]} rotation={[-Math.PI / 2, 0, 1.3]} scale={0.034}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_01420.geometry}
          material={materials['Material.007']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_01420_1.geometry}
          material={materials.AcademyWindowFrame}
        />
      </group>
      <group
        position={[-3.23, 0.308, -0.225]}
        rotation={[Math.PI, -1.568, 2.618]}
        scale={[0.067, 0.068, 0.068]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane001_1.geometry}
          material={materials['Material.009']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane001_2.geometry}
          material={materials['Material.089']}
        />
      </group>
      <group
        position={[-3.227, 0.313, 0.024]}
        rotation={[Math.PI, -1.568, Math.PI]}
        scale={[0.055, 0.062, 0.061]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane004_1.geometry}
          material={materials['Material.009']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane004_2.geometry}
          material={materials['Material.089']}
        />
      </group>
      <group
        position={[-3.228, 0.313, 0.12]}
        rotation={[Math.PI, -1.568, Math.PI]}
        scale={[0.068, 0.079, 0.068]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane003_1.geometry}
          material={materials['Material.009']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane003_2.geometry}
          material={materials['Material.089']}
        />
      </group>
      <group position={[-3.16, 0.313, 0.189]} rotation={[Math.PI, -1.568, Math.PI]} scale={0.068}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane006.geometry}
          material={materials['Material.009']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane006_1.geometry}
          material={materials['Material.089']}
        />
      </group>
      <group position={[-3.16, 0.313, 0.189]} rotation={[Math.PI, -1.568, Math.PI]} scale={0.068}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane024.geometry}
          material={materials['Material.009']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane024_1.geometry}
          material={materials['Material.089']}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.BoxTail.geometry}
        material={materials['Material.088']}
        position={[2.068, 0.525, -2.687]}
        rotation={[Math.PI / 2, 0, 2.404]}
        scale={[0.042, 0.042, 0.044]}
      />
      <group position={[2.062, 0.52, -2.647]} rotation={[Math.PI, -0.738, Math.PI]} scale={0.037}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.ModernPrimitiveBaseMesh005.geometry}
          material={materials['Material.010']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.ModernPrimitiveBaseMesh005_1.geometry}
          material={materials['Material.011']}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Post.geometry}
        material={materials.mMailbox}
        position={[2.02, 0.307, -2.61]}
        rotation={[-Math.PI / 2, 0, 2.309]}
        scale={0.085}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cluster_Verde_0.geometry}
        material={materials['Material.021']}
        position={[2.58, 0.704, -0.73]}
        rotation={[-Math.PI / 2, 0, 1.779]}
        scale={0.042}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cluster_Frente_0.geometry}
        material={materials['Frente.002']}
        position={[2.58, 0.704, -0.73]}
        rotation={[-Math.PI / 2, 0, 1.779]}
        scale={0.042}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cluster_MetalCase_0.geometry}
        material={materials['MetalCase.001']}
        position={[2.58, 0.704, -0.73]}
        rotation={[-Math.PI / 2, 0, 1.779]}
        scale={0.042}
      />
      <group position={[2.58, 0.704, -0.73]} rotation={[-Math.PI / 2, 0, 1.779]} scale={0.042}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cluster_Frente_0001_1.geometry}
          material={materials['Frente.002']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cluster_Frente_0001_2.geometry}
          material={materials['Material.021']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cluster_Frente_0001_3.geometry}
          material={materials['MetalCase.001']}
        />
      </group>
      <group position={[0.051, 0.411, 2.644]} rotation={[0, -0.016, 0]} scale={0.058}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.ModernPrimitiveBaseMesh.geometry}
          material={materials['Material.012']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.ModernPrimitiveBaseMesh_1.geometry}
          material={materials['material_0.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.ModernPrimitiveBaseMesh_2.geometry}
          material={materials.Emmision}
        />
      </group>
      <group
        position={[0.044, 0.423, 2.642]}
        rotation={[-Math.PI / 2, 0, -3.138]}
        scale={[0.014, 0.018, 0.016]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube009_Material004_0.geometry}
          material={materials['Material.012']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube009_Material004_0_1.geometry}
          material={materials['material_0.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube009_Material004_0_2.geometry}
          material={materials['Material.086']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube009_Material004_0_3.geometry}
          material={materials['Material.013']}
        />
      </group>
      <group
        position={[0.044, 0.423, 2.642]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[0.003, 0.003, 0.041]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder001_Material002_0.geometry}
          material={materials['material_0.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder001_Material002_0_1.geometry}
          material={materials['Material.085']}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Rails.geometry}
        material={materials['Metal.001']}
        position={[0.044, 0.411, 2.642]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.058}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.BBCourtBase.geometry}
        material={materials['Material.020']}
        position={[0.044, 0.411, 2.642]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.149}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane_Material003_0.geometry}
        material={materials['Material.087']}
        position={[0.044, 0.423, 2.642]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.128}
      />
      <group position={[0.774, 0.109, -4.458]} rotation={[-Math.PI, 0.425, -Math.PI]} scale={0.145}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube001_1.geometry}
          material={materials['FirstTexture.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube001_2.geometry}
          material={materials['Material.001']}
        />
      </group>
      <group position={[0.774, 0.096, -4.458]} rotation={[-Math.PI, 0.425, -Math.PI]} scale={0.76}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_0002.geometry}
          material={materials['FirstTexture.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_0002_1.geometry}
          material={materials['SecondTexture.001']}
        />
      </group>
    </a.group>
  )
}

export default Island;




