/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useEffect, useRef } from "react";
import { useAnimations, useGLTF } from "@react-three/drei";
import { a } from "@react-spring/three";
import islandScene from "../assets/3d/island4.glb";
import { useFrame, useThree } from "@react-three/fiber";

const Island = ({ isRotating, setIsRotating, setCurrentStage, setRotationSpeed, islandRotation, currentAnimation, ...props }) => {
  const islandRef = useRef();

  const { gl, viewport } = useThree();
  const { nodes, materials, animations, scene } = useGLTF(islandScene);
  const { actions } = useAnimations(animations, islandRef);
  

  const lastX = useRef(0);
  const rotationSpeed = useRef(0);
  const dampingFactor = 0.95;
  const rigRef = useRef();
  

  const handlePointerDown = (e) => {
    e.stopPropagation();
    e.preventDefault();
    setIsRotating(true);

    const clientX = e.touches
      ? e.touches[0].clientX
      : e.clientX;

    lastX.current = clientX;
  }

  const handlePointerUp = (e) => {
    e.stopPropagation();
    e.preventDefault();
    setIsRotating(false);
  }

  const handlePointerMove = (e) => {
    e.stopPropagation();
    e.preventDefault();

    if (isRotating) {
      const clientX = e.touches
        ? e.touches[0].clientX
        : e.clientX;

      const delta = (clientX - lastX.current) / viewport.width;

      islandRef.current.rotation.y += delta * Math.PI * 0.01;
      lastX.current = clientX;
      rotationSpeed.current = delta * 0.01 * Math.PI;
    }
  }

  const handleKeyDown = (e) => {
    if (e.key === "ArrowLeft") {
      if (!isRotating) setIsRotating(true);
      islandRef.current.rotation.y += 0.01 * Math.PI;
      rotationSpeed.current = 0.001 * Math.PI; // Update speed
    } else if (e.key === "ArrowRight") {
      if (!isRotating) setIsRotating(true);
      islandRef.current.rotation.y -= 0.01 * Math.PI;
      rotationSpeed.current = -0.001 * Math.PI; // Update speed
    }
  }

  const handleKeyUp = (e) => {
    if (e.key === "ArrowLeft" || e.key === "ArrowRight") {
      setIsRotating(false);
      rotationSpeed.current = 0; // Reset speed after release
    }
  }

  useFrame(() => {
    if (!isRotating) {
      rotationSpeed.current *= dampingFactor;

      if (Math.abs(rotationSpeed.current) < 0.0001) {
        rotationSpeed.current = 0;
      }

      islandRef.current.rotation.y += rotationSpeed.current;
    } else {
      const rotation = islandRef.current.rotation.y;

      const normalizedRotation = ((rotation % (2 * Math.PI)) + 2 * Math.PI) % (2 * Math.PI);

      // Set the current stage based on the island's orientation
      switch (true) {
        case normalizedRotation >= 3.1 && normalizedRotation <= 3.4:
          setCurrentStage(1);
          break;
        case normalizedRotation >= 3.8 && normalizedRotation <= 4.1:
          setCurrentStage(9);
          break;
        case normalizedRotation >= 4.5 && normalizedRotation <= 4.8:
          setCurrentStage(8);
          break;
        case normalizedRotation >= 5.2 && normalizedRotation <= 5.5:
          setCurrentStage(7);
          break;
        case normalizedRotation >= 5.9 && normalizedRotation <= 6.2:
          setCurrentStage(6);
          break;
        case normalizedRotation >= 0.6 && normalizedRotation <= 0.9:
          setCurrentStage(5);
          break;
        case normalizedRotation >= 1.3 && normalizedRotation <= 1.6:
          setCurrentStage(4);
          break;
        case normalizedRotation >= 2.0 && normalizedRotation <= 2.3:
          setCurrentStage(3);
          break;
        case normalizedRotation >= 2.7 && normalizedRotation <= 3.0:
          setCurrentStage(2);
          break;
        default:
          setCurrentStage(null);
      }
    }

    setRotationSpeed(rotationSpeed.current);
  })

  useEffect(() => {
    const canvas = gl.domElement;
    canvas.addEventListener("pointerdown", handlePointerDown);
    canvas.addEventListener("pointerup", handlePointerUp);
    canvas.addEventListener("pointercancel", handlePointerUp);
    canvas.addEventListener("pointermove", handlePointerMove);
    document.addEventListener("keydown", handleKeyDown);
    document.addEventListener("keyup", handleKeyUp);

    return () => {
      canvas.removeEventListener("pointerdown", handlePointerDown);
      canvas.removeEventListener("pointerup", handlePointerUp);
      canvas.removeEventListener("pointercancel", handlePointerUp);
      canvas.removeEventListener("pointermove", handlePointerMove);
      document.removeEventListener("keydown", handleKeyDown);
      document.removeEventListener("keyup", handleKeyUp);
    }
  }, [gl, handlePointerDown, handlePointerUp, handlePointerMove])

  useEffect(() => {
    if (!currentAnimation || !actions) return;
  
    Object.values(actions).forEach((action) => action.stop());
  
    if (actions[currentAnimation]) {
      actions[currentAnimation].reset().play();
    }
  }, [actions, currentAnimation]);
  
  useEffect(() => {
    console.log("Available animations:", Object.keys(actions));
  }, [actions]);
  
  

  /*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

  return (
    <a.group ref={islandRef} {...props}>
      <group name="Scene">
        <mesh
          name="Circle001"
          
          receiveShadow
          geometry={nodes.Circle001.geometry}
          material={materials['Material.014']}
          position={[0, 0.006, 0]}
          scale={[3.9, 4.682, 3.9]}
        />
        <group
          name="Capsule"
          position={[-1.958, 0.771, 1.695]}
          rotation={[Math.PI, -0.727, Math.PI]}
          scale={0.055}>
          <mesh
            name="Sphere001"
            castShadow
            receiveShadow
            geometry={nodes.Sphere001.geometry}
            material={materials['FirstTexture.001']}
          />
          <mesh
            name="Sphere001_1"
            castShadow
            receiveShadow
            geometry={nodes.Sphere001_1.geometry}
            material={materials['Material.001']}
          />
          <mesh
            name="Sphere001_2"
            castShadow
            receiveShadow
            geometry={nodes.Sphere001_2.geometry}
            material={materials['material_0.001']}
          />
          <mesh
            name="Sphere001_3"
            castShadow
            receiveShadow
            geometry={nodes.Sphere001_3.geometry}
            material={materials['Material.004']}
          />
          <mesh
            name="Sphere001_4"
            castShadow
            receiveShadow
            geometry={nodes.Sphere001_4.geometry}
            material={materials['Material.017']}
          />
          <mesh
            name="Sphere001_5"
            castShadow
            receiveShadow
            geometry={nodes.Sphere001_5.geometry}
            material={materials['Material.085']}
          />
        </group>
        <mesh
          name="Plane"
          
          receiveShadow
          geometry={nodes.Plane.geometry}
          material={materials['Material.015']}
          position={[0, 0.055, 0]}
          scale={52.327}
        />
        <group
          name="Camera"
          position={[748.113, 534.367, 650.764]}
          rotation={[3.127, 0.756, 2.69]}
          scale={100}>
          <group name="Object_23" />
        </group>
        <group
          name="Sketchfab_model001"
          position={[-3.135, 0.452, 0.337]}
          rotation={[-2.068, -0.045, -1.488]}
          scale={0.011}>
          <group name="cactuarobjcleanermaterialmergergles">
            <mesh
              name="Object_2001"
              castShadow
              receiveShadow
              geometry={nodes.Object_2001.geometry}
              material={materials.material0}
              position={[149.909, 90.105, 3.614]}
              rotation={[0.335, 0.113, 0.648]}
            />
          </group>
        </group>
        <mesh
          name="Circle002"
          castShadow
          receiveShadow
          geometry={nodes.Circle002.geometry}
          material={materials['Material.016']}
          position={[0, 0.324, 0]}
          scale={3.879}
        />
        <mesh
          name="Plane003"
          castShadow
          receiveShadow
          geometry={nodes.Plane003.geometry}
          material={nodes.Plane003.material}
          position={[-0.654, 2.237, -0.533]}
          rotation={[0, -0.141, 0]}
          scale={0.134}
        />
        <group
          name="Plane002"
          position={[0.579, 2.228, -0.527]}
          rotation={[Math.PI / 2, 0, -1.809]}
          scale={0.041}>
          <mesh
            name="Plane010"
            castShadow
            receiveShadow
            geometry={nodes.Plane010.geometry}
            material={materials['Material.004']}
          />
          <mesh
            name="Plane010_1"
            castShadow
            receiveShadow
            geometry={nodes.Plane010_1.geometry}
            material={materials['Material.003']}
          />
        </group>
        <group
          name="Plane001"
          position={[0.002, 2.228, -0.421]}
          rotation={[Math.PI / 2, 0, -1.575]}
          scale={0.041}>
          <mesh
            name="Plane009"
            castShadow
            receiveShadow
            geometry={nodes.Plane009.geometry}
            material={materials['Material.004']}
          />
          <mesh
            name="Plane009_1"
            castShadow
            receiveShadow
            geometry={nodes.Plane009_1.geometry}
            material={materials['Material.003']}
          />
        </group>
        <group
          name="Plane004"
          position={[-0.585, 2.228, -0.442]}
          rotation={[Math.PI / 2, 0, -1.358]}
          scale={0.041}>
          <mesh
            name="Plane007"
            castShadow
            receiveShadow
            geometry={nodes.Plane007.geometry}
            material={materials['Material.004']}
          />
          <mesh
            name="Plane007_1"
            castShadow
            receiveShadow
            geometry={nodes.Plane007_1.geometry}
            material={materials['Material.003']}
          />
        </group>
        <group
          name="Plane008"
          position={[-0.585, 2.228, -0.442]}
          rotation={[Math.PI / 2, 0, -1.358]}
          scale={0.041}>
          <mesh
            name="Plane020"
            castShadow
            receiveShadow
            geometry={nodes.Plane020.geometry}
            material={materials['Material.004']}
          />
          <mesh
            name="Plane020_1"
            castShadow
            receiveShadow
            geometry={nodes.Plane020_1.geometry}
            material={materials['Material.003']}
          />
        </group>
        <group
          name="PagodaTop"
          position={[2.428, 1.763, 1.457]}
          rotation={[0.026, 0.915, -0.009]}
          scale={0.058}>
          <mesh
            name="Plane017"
            castShadow
            receiveShadow
            geometry={nodes.Plane017.geometry}
            material={materials['Material.002']}
          />
          <mesh
            name="Plane017_1"
            castShadow
            receiveShadow
            geometry={nodes.Plane017_1.geometry}
            material={materials.Windows}
          />
        </group>
        <group
          name="Floor6"
          position={[2.427, 1.604, 1.454]}
          rotation={[0.026, 0.915, -0.009]}
          scale={[0.166, 0.163, 0.166]}>
          <mesh
            name="Plane015"
            castShadow
            receiveShadow
            geometry={nodes.Plane015.geometry}
            material={materials['Material.002']}
          />
          <mesh
            name="Plane015_1"
            castShadow
            receiveShadow
            geometry={nodes.Plane015_1.geometry}
            material={materials.Windows}
          />
        </group>
        <group
          name="Floor5"
          position={[2.426, 1.446, 1.451]}
          rotation={[0.026, 0.915, -0.009]}
          scale={[0.166, 0.163, 0.166]}>
          <mesh
            name="Plane014"
            castShadow
            receiveShadow
            geometry={nodes.Plane014.geometry}
            material={materials['Material.002']}
          />
          <mesh
            name="Plane014_1"
            castShadow
            receiveShadow
            geometry={nodes.Plane014_1.geometry}
            material={materials.Windows}
          />
        </group>
        <group
          name="Floor4"
          position={[2.425, 1.287, 1.448]}
          rotation={[0.026, 0.915, -0.009]}
          scale={[0.165, 0.163, 0.165]}>
          <mesh
            name="Plane013"
            castShadow
            receiveShadow
            geometry={nodes.Plane013.geometry}
            material={materials['Material.002']}
          />
          <mesh
            name="Plane013_1"
            castShadow
            receiveShadow
            geometry={nodes.Plane013_1.geometry}
            material={materials.Windows}
          />
        </group>
        <group
          name="Floor3"
          position={[2.424, 1.128, 1.445]}
          rotation={[0.026, 0.915, -0.009]}
          scale={[0.164, 0.163, 0.164]}>
          <mesh
            name="Plane012"
            castShadow
            receiveShadow
            geometry={nodes.Plane012.geometry}
            material={materials['Material.002']}
          />
          <mesh
            name="Plane012_1"
            castShadow
            receiveShadow
            geometry={nodes.Plane012_1.geometry}
            material={materials.Windows}
          />
        </group>
        <group
          name="Floor2"
          position={[2.423, 0.969, 1.442]}
          rotation={[0.026, 0.915, -0.009]}
          scale={0.163}>
          <mesh
            name="Plane011"
            castShadow
            receiveShadow
            geometry={nodes.Plane011.geometry}
            material={materials['Material.002']}
          />
          <mesh
            name="Plane011_1"
            castShadow
            receiveShadow
            geometry={nodes.Plane011_1.geometry}
            material={materials.Windows}
          />
        </group>
        <group
          name="Floor1"
          position={[2.422, 0.81, 1.439]}
          rotation={[0.026, 0.915, -0.009]}
          scale={0.163}>
          <mesh
            name="Plane002_1"
            castShadow
            receiveShadow
            geometry={nodes.Plane002_1.geometry}
            material={materials['Material.002']}
          />
          <mesh
            name="Plane002_2"
            castShadow
            receiveShadow
            geometry={nodes.Plane002_2.geometry}
            material={materials.Windows}
          />
        </group>
        <mesh
          name="Base"
          castShadow
          receiveShadow
          geometry={nodes.Base.geometry}
          material={materials['Pavillon-M.001']}
          position={[2.418, 0.452, 1.431]}
          rotation={[-1.552, 0.006, 0.915]}
          scale={0.295}
        />
        <group
          name="Taiper101Door"
          position={[2.418, 0.453, 1.431]}
          rotation={[-1.552, 0.006, 0.915]}
          scale={0.295}>
          <mesh
            name="BUR_T6_4_PERRONE_01_Material_0013"
            castShadow
            receiveShadow
            geometry={nodes.BUR_T6_4_PERRONE_01_Material_0013.geometry}
            material={materials['Material.002']}
          />
          <mesh
            name="BUR_T6_4_PERRONE_01_Material_0013_1"
            castShadow
            receiveShadow
            geometry={nodes.BUR_T6_4_PERRONE_01_Material_0013_1.geometry}
            material={materials.Windows}
          />
        </group>
        <group
          name="BuildingBody"
          position={[2.418, 0.453, 1.431]}
          rotation={[-1.552, 0.006, 0.915]}
          scale={0.295}>
          <mesh
            name="BUR_T6_4_PERRONE_01_Material_0012"
            castShadow
            receiveShadow
            geometry={nodes.BUR_T6_4_PERRONE_01_Material_0012.geometry}
            material={materials['Material.002']}
          />
          <mesh
            name="BUR_T6_4_PERRONE_01_Material_0012_1"
            castShadow
            receiveShadow
            geometry={nodes.BUR_T6_4_PERRONE_01_Material_0012_1.geometry}
            material={materials.Metal}
          />
        </group>
        <group
          name="Taipei101CircleThing"
          position={[2.418, 0.453, 1.431]}
          rotation={[-1.552, 0.006, 0.915]}
          scale={0.295}>
          <mesh
            name="BUR_T6_4_PERRONE_01_Material_0002"
            castShadow
            receiveShadow
            geometry={nodes.BUR_T6_4_PERRONE_01_Material_0002.geometry}
            material={materials['Material.002']}
          />
          <mesh
            name="BUR_T6_4_PERRONE_01_Material_0002_1"
            castShadow
            receiveShadow
            geometry={nodes.BUR_T6_4_PERRONE_01_Material_0002_1.geometry}
            material={materials['Material.001']}
          />
        </group>
        <group
          name="Taipei101"
          position={[2.384, 0.415, 1.406]}
          rotation={[-1.552, 0.006, 0.915]}
          scale={0.295}>
          <mesh
            name="BUR_T6_4_PERRONE_01001_Pavillon-M001_0001"
            castShadow
            receiveShadow
            geometry={nodes['BUR_T6_4_PERRONE_01001_Pavillon-M001_0001'].geometry}
            material={materials['Pavillon-M.001']}
          />
          <mesh
            name="BUR_T6_4_PERRONE_01001_Pavillon-M001_0001_1"
            castShadow
            receiveShadow
            geometry={nodes['BUR_T6_4_PERRONE_01001_Pavillon-M001_0001_1'].geometry}
            material={materials['Material.002']}
          />
          <mesh
            name="BUR_T6_4_PERRONE_01001_Pavillon-M001_0001_2"
            castShadow
            receiveShadow
            geometry={nodes['BUR_T6_4_PERRONE_01001_Pavillon-M001_0001_2'].geometry}
            material={materials.Windows}
          />
          <mesh
            name="BUR_T6_4_PERRONE_01001_Pavillon-M001_0001_3"
            castShadow
            receiveShadow
            geometry={nodes['BUR_T6_4_PERRONE_01001_Pavillon-M001_0001_3'].geometry}
            material={materials.Metal}
          />
          <mesh
            name="BUR_T6_4_PERRONE_01001_Pavillon-M001_0001_4"
            castShadow
            receiveShadow
            geometry={nodes['BUR_T6_4_PERRONE_01001_Pavillon-M001_0001_4'].geometry}
            material={materials['Material.001']}
          />
        </group>
        <group
          name="Academy_Body"
          position={[-1.882, 0.379, -2.067]}
          rotation={[-Math.PI / 2, 0, 1.3]}
          scale={0.034}>
          <mesh
            name="Object_0004"
            castShadow
            receiveShadow
            geometry={nodes.Object_0004.geometry}
            material={materials.School}
          />
          <mesh
            name="Object_0004_1"
            castShadow
            receiveShadow
            geometry={nodes.Object_0004_1.geometry}
            material={materials['Material.005']}
          />
          <mesh
            name="Object_0004_2"
            castShadow
            receiveShadow
            geometry={nodes.Object_0004_2.geometry}
            material={materials['Material.006']}
          />
          <mesh
            name="Object_0004_3"
            castShadow
            receiveShadow
            geometry={nodes.Object_0004_3.geometry}
            material={materials.Material}
          />
          <mesh
            name="Object_0004_4"
            castShadow
            receiveShadow
            geometry={nodes.Object_0004_4.geometry}
            material={materials['Material.007']}
          />
          <mesh
            name="Object_0004_5"
            castShadow
            receiveShadow
            geometry={nodes.Object_0004_5.geometry}
            material={materials.AcademyWindowFrame}
          />
        </group>
        <mesh
          name="Box2"
          castShadow
          receiveShadow
          geometry={nodes.Box2.geometry}
          material={materials.AcademyWindowFrame}
          position={[-1.764, 0.385, -2.098]}
          rotation={[-Math.PI / 2, 0, 1.3]}
          scale={0.034}
        />
        <group
          name="ACUnitDual"
          position={[-1.764, 0.385, -2.098]}
          rotation={[-Math.PI / 2, 0, 1.3]}
          scale={0.034}>
          <mesh
            name="Object_01341"
            castShadow
            receiveShadow
            geometry={nodes.Object_01341.geometry}
            material={materials.AcademyWindowFrame}
          />
          <mesh
            name="Object_01341_1"
            castShadow
            receiveShadow
            geometry={nodes.Object_01341_1.geometry}
            material={materials['Material.008']}
          />
          <mesh
            name="Object_01341_2"
            castShadow
            receiveShadow
            geometry={nodes.Object_01341_2.geometry}
            material={materials.Frente}
          />
        </group>
        <mesh
          name="CeilingWindow"
          castShadow
          receiveShadow
          geometry={nodes.CeilingWindow.geometry}
          material={materials.School}
          position={[-1.764, 0.385, -2.098]}
          rotation={[-Math.PI / 2, 0, 1.3]}
          scale={0.034}
        />
        <mesh
          name="Box"
          castShadow
          receiveShadow
          geometry={nodes.Box.geometry}
          material={materials.AcademyWindowFrame}
          position={[-1.764, 0.385, -2.098]}
          rotation={[-Math.PI / 2, 0, 1.3]}
          scale={0.034}
        />
        <group
          name="ACUnit"
          position={[-1.764, 0.385, -2.098]}
          rotation={[-Math.PI / 2, 0, 1.3]}
          scale={0.034}>
          <mesh
            name="Object_01264"
            castShadow
            receiveShadow
            geometry={nodes.Object_01264.geometry}
            material={materials.AcademyWindowFrame}
          />
          <mesh
            name="Object_01264_1"
            castShadow
            receiveShadow
            geometry={nodes.Object_01264_1.geometry}
            material={materials['Material.008']}
          />
          <mesh
            name="Object_01264_2"
            castShadow
            receiveShadow
            geometry={nodes.Object_01264_2.geometry}
            material={materials.Frente}
          />
        </group>
        <mesh
          name="Chimney"
          castShadow
          receiveShadow
          geometry={nodes.Chimney.geometry}
          material={nodes.Chimney.material}
          position={[-1.555, 0.958, -1.907]}
          rotation={[0, 1.3, 0]}
          scale={0.034}
        />
        <group
          name="BigWindowMiddle"
          position={[-1.764, 0.385, -2.098]}
          rotation={[-Math.PI / 2, 0, 1.3]}
          scale={0.034}>
          <mesh
            name="Object_01421"
            castShadow
            receiveShadow
            geometry={nodes.Object_01421.geometry}
            material={materials['Material.007']}
          />
          <mesh
            name="Object_01421_1"
            castShadow
            receiveShadow
            geometry={nodes.Object_01421_1.geometry}
            material={materials.AcademyWindowFrame}
          />
        </group>
        <group
          name="ArchWindowMiddle"
          position={[-1.764, 0.385, -2.098]}
          rotation={[-Math.PI / 2, 0, 1.3]}
          scale={0.034}>
          <mesh
            name="Object_01420"
            castShadow
            receiveShadow
            geometry={nodes.Object_01420.geometry}
            material={materials['Material.007']}
          />
          <mesh
            name="Object_01420_1"
            castShadow
            receiveShadow
            geometry={nodes.Object_01420_1.geometry}
            material={materials.AcademyWindowFrame}
          />
        </group>
        <group
          name="BookCover1003"
          position={[-3.23, 0.308, -0.225]}
          rotation={[Math.PI, -1.568, 2.618]}
          scale={[0.067, 0.068, 0.068]}>
          <mesh
            name="Plane001_1"
            castShadow
            receiveShadow
            geometry={nodes.Plane001_1.geometry}
            material={materials['Material.009']}
          />
          <mesh
            name="Plane001_2"
            castShadow
            receiveShadow
            geometry={nodes.Plane001_2.geometry}
            material={materials['Material.089']}
          />
        </group>
        <group
          name="BookCover1002"
          position={[-3.227, 0.313, 0.024]}
          rotation={[Math.PI, -1.568, Math.PI]}
          scale={[0.055, 0.062, 0.061]}>
          <mesh
            name="Plane004_1"
            castShadow
            receiveShadow
            geometry={nodes.Plane004_1.geometry}
            material={materials['Material.009']}
          />
          <mesh
            name="Plane004_2"
            castShadow
            receiveShadow
            geometry={nodes.Plane004_2.geometry}
            material={materials['Material.089']}
          />
        </group>
        <group
          name="BookCover1001"
          position={[-3.228, 0.313, 0.12]}
          rotation={[Math.PI, -1.568, Math.PI]}
          scale={[0.068, 0.079, 0.068]}>
          <mesh
            name="Plane003_1"
            castShadow
            receiveShadow
            geometry={nodes.Plane003_1.geometry}
            material={materials['Material.009']}
          />
          <mesh
            name="Plane003_2"
            castShadow
            receiveShadow
            geometry={nodes.Plane003_2.geometry}
            material={materials['Material.089']}
          />
        </group>
        <group
          name="BookCover1"
          position={[-3.16, 0.313, 0.189]}
          rotation={[Math.PI, -1.568, Math.PI]}
          scale={0.068}>
          <mesh
            name="Plane006"
            castShadow
            receiveShadow
            geometry={nodes.Plane006.geometry}
            material={materials['Material.009']}
          />
          <mesh
            name="Plane006_1"
            castShadow
            receiveShadow
            geometry={nodes.Plane006_1.geometry}
            material={materials['Material.089']}
          />
        </group>
        <group
          name="BookCover1007"
          position={[-3.16, 0.313, 0.189]}
          rotation={[Math.PI, -1.568, Math.PI]}
          scale={0.068}>
          <mesh
            name="Plane024"
            castShadow
            receiveShadow
            geometry={nodes.Plane024.geometry}
            material={materials['Material.009']}
          />
          <mesh
            name="Plane024_1"
            castShadow
            receiveShadow
            geometry={nodes.Plane024_1.geometry}
            material={materials['Material.089']}
          />
        </group>
        <mesh
          name="BoxTail"
          castShadow
          receiveShadow
          geometry={nodes.BoxTail.geometry}
          material={materials['Material.088']}
          position={[2.068, 0.525, -2.687]}
          rotation={[Math.PI / 2, 0, 2.404]}
          scale={[0.042, 0.042, 0.044]}
        />
        <mesh
          name="Cluster_Verde_0"
          castShadow
          receiveShadow
          geometry={nodes.Cluster_Verde_0.geometry}
          material={materials['Material.021']}
          position={[2.468, 0.68, -0.706]}
          rotation={[-Math.PI / 2, 0, 1.779]}
          scale={0.042}
        />
        <mesh
          name="Cluster_Frente_0"
          castShadow
          receiveShadow
          geometry={nodes.Cluster_Frente_0.geometry}
          material={materials['Frente.002']}
          position={[2.468, 0.68, -0.706]}
          rotation={[-Math.PI / 2, 0, 1.779]}
          scale={0.042}
        />
        <mesh
          name="Cluster_MetalCase_0"
          castShadow
          receiveShadow
          geometry={nodes.Cluster_MetalCase_0.geometry}
          material={materials['MetalCase.001']}
          position={[2.468, 0.68, -0.706]}
          rotation={[-Math.PI / 2, 0, 1.779]}
          scale={0.042}
        />
        <group
          name="Cluster_Frente_0001"
          position={[2.58, 0.704, -0.73]}
          rotation={[-Math.PI / 2, 0, 1.779]}
          scale={0.042}>
          <mesh
            name="Cluster_Frente_0001_1"
            castShadow
            receiveShadow
            geometry={nodes.Cluster_Frente_0001_1.geometry}
            material={materials['Frente.002']}
          />
          <mesh
            name="Cluster_Frente_0001_2"
            castShadow
            receiveShadow
            geometry={nodes.Cluster_Frente_0001_2.geometry}
            material={materials['Material.021']}
          />
          <mesh
            name="Cluster_Frente_0001_3"
            castShadow
            receiveShadow
            geometry={nodes.Cluster_Frente_0001_3.geometry}
            material={materials['MetalCase.001']}
          />
        </group>
        <group name="Lamp" position={[0.052, 0.341, 2.644]} rotation={[0, -0.016, 0]} scale={0.062}>
          <mesh
            name="ModernPrimitiveBaseMesh"
            castShadow
            receiveShadow
            geometry={nodes.ModernPrimitiveBaseMesh.geometry}
            material={materials['Material.012']}
          />
          <mesh
            name="ModernPrimitiveBaseMesh_1"
            castShadow
            receiveShadow
            geometry={nodes.ModernPrimitiveBaseMesh_1.geometry}
            material={materials['material_0.001']}
          />
          <mesh
            name="ModernPrimitiveBaseMesh_2"
            castShadow
            receiveShadow
            geometry={nodes.ModernPrimitiveBaseMesh_2.geometry}
            material={materials.Emmision}
          />
        </group>
        <group
          name="Hoop"
          position={[0.044, 0.354, 2.642]}
          rotation={[-Math.PI / 2, 0, -3.138]}
          scale={[0.015, 0.02, 0.017]}>
          <mesh
            name="Cube009_Material004_0"
            castShadow
            receiveShadow
            geometry={nodes.Cube009_Material004_0.geometry}
            material={materials['Material.012']}
          />
          <mesh
            name="Cube009_Material004_0_1"
            castShadow
            receiveShadow
            geometry={nodes.Cube009_Material004_0_1.geometry}
            material={materials['material_0.001']}
          />
          <mesh
            name="Cube009_Material004_0_2"
            castShadow
            receiveShadow
            geometry={nodes.Cube009_Material004_0_2.geometry}
            material={materials['Material.086']}
          />
          <mesh
            name="Cube009_Material004_0_3"
            castShadow
            receiveShadow
            geometry={nodes.Cube009_Material004_0_3.geometry}
            material={materials['Material.013']}
          />
        </group>
        <group
          name="Chair"
          position={[0.044, 0.354, 2.642]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[0.003, 0.003, 0.044]}>
          <mesh
            name="Cylinder001_Material002_0"
            castShadow
            receiveShadow
            geometry={nodes.Cylinder001_Material002_0.geometry}
            material={materials['material_0.001']}
          />
          <mesh
            name="Cylinder001_Material002_0_1"
            castShadow
            receiveShadow
            geometry={nodes.Cylinder001_Material002_0_1.geometry}
            material={materials['Material.085']}
          />
        </group>
        <mesh
          name="Rails"
          castShadow
          receiveShadow
          geometry={nodes.Rails.geometry}
          material={materials['Metal.001']}
          position={[0.044, 0.341, 2.642]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={0.062}
        />
        <mesh
          name="BBCourtBase"
          castShadow
          receiveShadow
          geometry={nodes.BBCourtBase.geometry}
          material={materials['Material.020']}
          position={[0.044, 0.341, 2.642]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={0.16}
        />
        <mesh
          name="Plane_Material003_0"
          castShadow
          receiveShadow
          geometry={nodes.Plane_Material003_0.geometry}
          material={materials['Material.087']}
          position={[0.044, 0.354, 2.642]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={0.137}
        />
        <group
          name="Cube001"
          position={[0.774, 0.109, -4.458]}
          rotation={[-Math.PI, 0.425, -Math.PI]}
          scale={0.145}>
          <mesh
            name="Cube001_1"
            castShadow
            receiveShadow
            geometry={nodes.Cube001_1.geometry}
            material={materials['FirstTexture.001']}
          />
          <mesh
            name="Cube001_2"
            castShadow
            receiveShadow
            geometry={nodes.Cube001_2.geometry}
            material={materials['Material.001']}
          />
        </group>
        <group
          name="FerryBody"
          position={[0.774, 0.096, -4.458]}
          rotation={[-Math.PI, 0.425, -Math.PI]}
          scale={0.76}>
          <mesh
            name="Object_0002"
            castShadow
            receiveShadow
            geometry={nodes.Object_0002.geometry}
            material={materials['FirstTexture.001']}
          />
          <mesh
            name="Object_0002_1"
            castShadow
            receiveShadow
            geometry={nodes.Object_0002_1.geometry}
            material={materials['SecondTexture.001']}
          />
        </group>
        <group
          name="Mailbox"
          position={[2.065, 0.554, -2.657]}
          rotation={[Math.PI, -0.876, Math.PI]}
          scale={0.049}>
          <mesh
            name="ModernPrimitiveBaseMesh005"
            castShadow
            receiveShadow
            geometry={nodes.ModernPrimitiveBaseMesh005.geometry}
            material={materials['Material.010']}
          />
          <mesh
            name="ModernPrimitiveBaseMesh005_1"
            castShadow
            receiveShadow
            geometry={nodes.ModernPrimitiveBaseMesh005_1.geometry}
            material={materials['Material.011']}
          />
        </group>
        <mesh
          name="Post"
          castShadow
          receiveShadow
          geometry={nodes.Post.geometry}
          material={materials.mMailbox}
          position={[2.017, 0.273, -2.6]}
          rotation={[-Math.PI / 2, 0, 2.447]}
          scale={0.112}
        />
        <mesh
          name="Cone003"
          castShadow
          receiveShadow
          geometry={nodes.Cone003.geometry}
          material={materials['Material.018']}
          position={[0.533, 1.343, -1.001]}
          rotation={[-2.89, 1.278, 2.86]}
          scale={[0.061, 0.08, 0.061]}
        />
        <mesh
          name="Cone004"
          castShadow
          receiveShadow
          geometry={nodes.Cone004.geometry}
          material={materials['Material.018']}
          position={[0.533, 1.42, -0.838]}
          rotation={[-3.114, 1.283, 3.095]}
          scale={[0.079, 0.105, 0.079]}
        />
        <mesh
          name="Cone005"
          castShadow
          receiveShadow
          geometry={nodes.Cone005.geometry}
          material={materials['Material.018']}
          position={[0.328, 1.351, -0.904]}
          rotation={[0.12, 1.468, -0.141]}
          scale={[0.109, 0.145, 0.109]}
        />
        <group
          name="Sketchfab_model002"
          position={[-4.016, 0.387, -1.9]}
          rotation={[-1.725, -0.06, -1.995]}
          scale={0.359}>
          <group name="Collada_visual_scene_group" rotation={[Math.PI / 2, 0, 0]}>
            <group name="Cube002">
              <mesh
                name="defaultMaterial"
                castShadow
                receiveShadow
                geometry={nodes.defaultMaterial.geometry}
                material={materials.DefaultMaterial}
              />
            </group>
          </group>
        </group>
        <group
          name="Sketchfab_model"
          position={[2.276, 0.319, -2.452]}
          rotation={[0, 2.5, 0]}
          scale={0.303}>
          <group name="idle_m_2_220ffbx" scale={0.01} >
            <group name="Object_2">
              <group name="RootNode" >
                <group name="lpMaleG" />
                <group name="rig_CharRoot" rotation={[-Math.PI / 2, 0, 0]}>
                  <group name="Object_6">
                    <group name="Object_8" />
                    <skinnedMesh
                      name="Object_9" 
                      geometry={nodes.Object_9.geometry}
                      material={materials['peopleColors.001']}
                      skeleton={nodes.Object_9.skeleton}
                    />
                    <primitive object={nodes._rootJoint} />
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
        <mesh
          name="Icosphere"
          castShadow
          receiveShadow
          geometry={nodes.Icosphere.geometry}
          material={nodes.Icosphere.material}
        />
        <mesh
          name="Icosphere001"
          castShadow
          receiveShadow
          geometry={nodes.Icosphere001.geometry}
          material={nodes.Icosphere001.material}
        />
        <mesh
          name="Icosphere002"
          castShadow
          receiveShadow
          geometry={nodes.Icosphere002.geometry}
          material={nodes.Icosphere002.material}
        />
        <mesh
          name="Icosphere003"
          castShadow
          receiveShadow
          geometry={nodes.Icosphere003.geometry}
          material={nodes.Icosphere003.material}
        />
        <mesh
          name="Icosphere004"
          castShadow
          receiveShadow
          geometry={nodes.Icosphere004.geometry}
          material={nodes.Icosphere004.material}
        />
        <mesh
          name="Cone"
          castShadow
          receiveShadow
          geometry={nodes.Cone.geometry}
          material={materials['Material.019']}
          position={[0.189, 0.928, 0.721]}
          rotation={[-0.786, 1.493, 0.763]}
          scale={[0.122, 0.161, 0.122]}
        />
        <mesh
          name="Cone002"
          castShadow
          receiveShadow
          geometry={nodes.Cone002.geometry}
          material={materials['Material.019']}
          position={[0.299, 1.025, 0.958]}
          rotation={[-2.808, 1.243, 2.77]}
          scale={[0.07, 0.093, 0.07]}
        />
        <mesh
          name="Cone006"
          castShadow
          receiveShadow
          geometry={nodes.Cone006.geometry}
          material={materials['Material.022']}
          position={[1.881, 0.343, 1.913]}
          rotation={[-2.981, 1.292, 2.926]}
          scale={[0.116, 0.154, 0.116]}
        />
        <mesh
          name="Cone007"
          castShadow
          receiveShadow
          geometry={nodes.Cone007.geometry}
          material={materials['Material.022']}
          position={[2.029, 0.276, 2.074]}
          rotation={[-3.114, 1.283, 3.095]}
          scale={[0.111, 0.148, 0.111]}
        />
        <mesh
          name="Cone008"
          castShadow
          receiveShadow
          geometry={nodes.Cone008.geometry}
          material={materials['Material.022']}
          position={[1.828, 0.368, 2.154]}
          rotation={[0.12, 1.468, -0.141]}
          scale={[0.094, 0.125, 0.094]}
        />
        <mesh
          name="Cone009"
          castShadow
          receiveShadow
          geometry={nodes.Cone009.geometry}
          material={materials['Material.023']}
          position={[2.591, 0.327, 0.752]}
          rotation={[-3.114, 1.283, 3.095]}
          scale={[0.091, 0.121, 0.091]}
        />
        <mesh
          name="Cone011"
          castShadow
          receiveShadow
          geometry={nodes.Cone011.geometry}
          material={materials['Material.024']}
          position={[-1.649, 0.046, -4.242]}
          rotation={[-3.114, 1.283, 3.095]}
          scale={[0.103, 0.137, 0.103]}
        />
        <mesh
          name="Cone012"
          castShadow
          receiveShadow
          geometry={nodes.Cone012.geometry}
          material={materials['Material.024']}
          position={[-2.504, 0.232, -2.274]}
          rotation={[-2.985, 1.34, 2.987]}
          scale={[0.097, 0.129, 0.097]}
        />
        <mesh
          name="Cone013"
          castShadow
          receiveShadow
          geometry={nodes.Cone013.geometry}
          material={materials['Material.025']}
          position={[-3.67, 0.134, 2.24]}
          rotation={[0.052, -1.148, 0.085]}
          scale={[0.115, 0.152, 0.115]}
        />
        <mesh
          name="Cone014"
          castShadow
          receiveShadow
          geometry={nodes.Cone014.geometry}
          material={materials['Material.025']}
          position={[-2.629, 0.306, -1.541]}
          rotation={[0.081, -1.146, 0.184]}
          scale={[0.082, 0.109, 0.082]}
        />
        <mesh
          name="Cone015"
          castShadow
          receiveShadow
          geometry={nodes.Cone015.geometry}
          material={materials['Material.025']}
          position={[-2.71, 0.22, 0.715]}
          rotation={[1.569, -1.473, 1.54]}
          scale={[0.113, 0.15, 0.113]}
        />
        <mesh
          name="Cone016"
          castShadow
          receiveShadow
          geometry={nodes.Cone016.geometry}
          material={materials['Material.026']}
          position={[-0.708, 0.193, -3.103]}
          rotation={[-2.89, 1.278, 2.86]}
          scale={[0.07, 0.093, 0.07]}
        />
        <mesh
          name="Cone017"
          castShadow
          receiveShadow
          geometry={nodes.Cone017.geometry}
          material={materials['Material.026']}
          position={[0.941, 0.278, -2.279]}
          rotation={[-3.114, 1.283, 3.095]}
          scale={[0.132, 0.175, 0.132]}
        />
        <mesh
          name="Cone018"
          castShadow
          receiveShadow
          geometry={nodes.Cone018.geometry}
          material={materials['Material.026']}
          position={[-2.342, 0.271, -1.614]}
          rotation={[0.12, 1.468, -0.141]}
          scale={[0.052, 0.069, 0.052]}
        />
        <mesh
          name="Cone019"
          castShadow
          receiveShadow
          geometry={nodes.Cone019.geometry}
          material={materials['Material.027']}
          position={[-0.913, 0.213, -2.521]}
          rotation={[-0.346, 1.432, 0.272]}
          scale={[0.128, 0.169, 0.128]}
        />
        <mesh
          name="Cone020"
          castShadow
          receiveShadow
          geometry={nodes.Cone020.geometry}
          material={materials['Material.027']}
          position={[-2.301, 0.238, -1.499]}
          rotation={[-3.114, 1.283, 3.095]}
          scale={[0.122, 0.161, 0.122]}
        />
        <mesh
          name="Cone022"
          castShadow
          receiveShadow
          geometry={nodes.Cone022.geometry}
          material={materials['Material.028']}
          position={[-2.429, 0.238, 0.603]}
          rotation={[-2.89, 1.278, 2.86]}
          scale={[0.127, 0.169, 0.127]}
        />
        <mesh
          name="Cone023"
          castShadow
          receiveShadow
          geometry={nodes.Cone023.geometry}
          material={materials['Material.028']}
          position={[-3.242, 0.04, 2.772]}
          rotation={[-3.114, 1.283, 3.095]}
          scale={[0.147, 0.195, 0.147]}
        />
        <mesh
          name="Cone024"
          castShadow
          receiveShadow
          geometry={nodes.Cone024.geometry}
          material={materials['Material.028']}
          position={[-0.541, 1.36, -0.969]}
          rotation={[-0.276, 1.427, 0.306]}
          scale={[0.114, 0.151, 0.114]}
        />
        <mesh
          name="Cone025"
          castShadow
          receiveShadow
          geometry={nodes.Cone025.geometry}
          material={materials['Material.029']}
          position={[-0.783, 1.446, -0.684]}
          rotation={[-0.1, -1.517, -0.002]}
          scale={[0.069, 0.092, 0.069]}
        />
        <mesh
          name="Cone027"
          castShadow
          receiveShadow
          geometry={nodes.Cone027.geometry}
          material={materials['Material.030']}
          position={[0.958, 0.251, -2.546]}
          rotation={[-3.114, 1.283, 3.095]}
          scale={[0.088, 0.116, 0.088]}
        />
        <mesh
          name="Cone028"
          castShadow
          receiveShadow
          geometry={nodes.Cone028.geometry}
          material={materials['Material.030']}
          position={[-1.012, 0.315, -2.032]}
          rotation={[-3.067, 1.258, 3.066]}
          scale={[0.109, 0.145, 0.109]}
        />
        <mesh
          name="Cone029"
          castShadow
          receiveShadow
          geometry={nodes.Cone029.geometry}
          material={materials['Material.031']}
          position={[-3.637, 0.09, 2.397]}
          rotation={[-2.89, 1.278, 2.86]}
          scale={[0.102, 0.135, 0.102]}
        />
        <mesh
          name="Cone030"
          castShadow
          receiveShadow
          geometry={nodes.Cone030.geometry}
          material={materials['Material.032']}
          position={[1.874, 0.275, -1.321]}
          rotation={[-3.114, 1.283, 3.095]}
          scale={[0.122, 0.161, 0.122]}
        />
        <mesh
          name="Cone031"
          castShadow
          receiveShadow
          geometry={nodes.Cone031.geometry}
          material={materials['Material.033']}
          position={[-1.12, 0.328, 1.455]}
          rotation={[-3.114, 1.283, 3.095]}
          scale={[0.098, 0.13, 0.098]}
        />
        <mesh
          name="Cone032"
          castShadow
          receiveShadow
          geometry={nodes.Cone032.geometry}
          material={materials['Material.033']}
          position={[-1.359, 0.311, 1.31]}
          rotation={[0.12, 1.468, -0.141]}
          scale={[0.135, 0.18, 0.135]}
        />
        <mesh
          name="Cone033"
          castShadow
          receiveShadow
          geometry={nodes.Cone033.geometry}
          material={materials['Material.034']}
          position={[-1.406, 0.176, 2.291]}
          rotation={[0.12, 1.468, -0.141]}
          scale={[0.189, 0.251, 0.189]}
        />
        <mesh
          name="Cone034"
          castShadow
          receiveShadow
          geometry={nodes.Cone034.geometry}
          material={materials['Material.035']}
          position={[1.512, 0.268, 2.378]}
          rotation={[-0.42, 1.466, 0.427]}
          scale={[0.144, 0.191, 0.144]}
        />
        <mesh
          name="Cone035"
          castShadow
          receiveShadow
          geometry={nodes.Cone035.geometry}
          material={materials['Material.036']}
          position={[0.437, 0.853, 0.765]}
          rotation={[-3.114, 1.283, 3.095]}
          scale={[0.129, 0.171, 0.129]}
        />
        <mesh
          name="Cone036"
          castShadow
          receiveShadow
          geometry={nodes.Cone036.geometry}
          material={materials['Material.037']}
          position={[-0.03, 1.404, -0.107]}
          rotation={[-2.89, 1.278, 2.86]}
          scale={[0.094, 0.124, 0.094]}
        />
        <mesh
          name="Cone037"
          castShadow
          receiveShadow
          geometry={nodes.Cone037.geometry}
          material={materials['Material.038']}
          position={[-2.559, 0.307, 0.809]}
          rotation={[-0.139, -1.159, -0.121]}
          scale={[0.082, 0.109, 0.082]}
        />
        <mesh
          name="Cone038"
          castShadow
          receiveShadow
          geometry={nodes.Cone038.geometry}
          material={materials['Material.039']}
          position={[2.962, 0.256, 0.528]}
          rotation={[-3.009, 1.272, 3.026]}
          scale={[0.088, 0.116, 0.088]}
        />
        <mesh
          name="Cone039"
          castShadow
          receiveShadow
          geometry={nodes.Cone039.geometry}
          material={materials['Material.040']}
          position={[2.687, 0.254, 0.531]}
          rotation={[-3.009, 1.272, 3.026]}
          scale={[0.132, 0.175, 0.132]}
        />
        <mesh
          name="Cone001"
          castShadow
          receiveShadow
          geometry={nodes.Cone001.geometry}
          material={materials['Material.041']}
          position={[-4.234, 0.17, -0.228]}
          rotation={[-0.139, -1.159, -0.121]}
          scale={[0.082, 0.109, 0.082]}
        />
        <mesh
          name="Cone010"
          castShadow
          receiveShadow
          geometry={nodes.Cone010.geometry}
          material={materials['Material.042']}
          position={[-4.103, 0.101, -0.435]}
          rotation={[-2.89, 1.278, 2.86]}
          scale={[0.127, 0.169, 0.127]}
        />
        <mesh
          name="Cone021"
          castShadow
          receiveShadow
          geometry={nodes.Cone021.geometry}
          material={materials['Material.043']}
          position={[-4.385, 0.084, -0.323]}
          rotation={[1.569, -1.473, 1.54]}
          scale={[0.113, 0.15, 0.113]}
        />
        <mesh
          name="Cone026"
          castShadow
          receiveShadow
          geometry={nodes.Cone026.geometry}
          material={materials['Material.044']}
          position={[-3.405, -0.024, 2.495]}
          rotation={[0.12, 1.468, -0.141]}
          scale={[0.189, 0.251, 0.189]}
        />
        <mesh
          name="Cone040"
          castShadow
          receiveShadow
          geometry={nodes.Cone040.geometry}
          material={materials['Material.045']}
          position={[0.839, 0.237, -2.377]}
          rotation={[-2.89, 1.278, 2.86]}
          scale={[0.07, 0.093, 0.07]}
        />
        <mesh
          name="Cone041"
          castShadow
          receiveShadow
          geometry={nodes.Cone041.geometry}
          material={materials['Material.046']}
          position={[0.134, 1.428, -0.189]}
          rotation={[-2.89, 1.278, 2.86]}
          scale={[0.061, 0.08, 0.061]}
        />
        <mesh
          name="Cone042"
          castShadow
          receiveShadow
          geometry={nodes.Cone042.geometry}
          material={materials['Material.047']}
          position={[-0.004, 1.475, -0.235]}
          rotation={[-0.127, -1.491, -0.076]}
          scale={[0.069, 0.092, 0.069]}
        />
        <mesh
          name="Cone043"
          castShadow
          receiveShadow
          geometry={nodes.Cone043.geometry}
          material={materials['Material.048']}
          position={[1.09, 0.297, -2.387]}
          rotation={[-2.89, 1.278, 2.86]}
          scale={[0.07, 0.093, 0.07]}
        />
        <mesh
          name="Cone044"
          castShadow
          receiveShadow
          geometry={nodes.Cone044.geometry}
          material={materials['Material.049']}
          position={[-2.791, 0.181, 3.084]}
          rotation={[-0.05, 0.475, 0.03]}
          scale={[0.082, 0.109, 0.082]}
        />
        <mesh
          name="Cone045"
          castShadow
          receiveShadow
          geometry={nodes.Cone045.geometry}
          material={materials['Material.050']}
          position={[-3.001, 0.086, 2.975]}
          rotation={[3.14, -0.35, 3.082]}
          scale={[0.127, 0.169, 0.127]}
        />
        <mesh
          name="Cone046"
          castShadow
          receiveShadow
          geometry={nodes.Cone046.geometry}
          material={materials['Material.051']}
          position={[-2.871, 0.105, 3.249]}
          rotation={[-0.006, 0.066, 0.032]}
          scale={[0.113, 0.15, 0.113]}
        />
        <mesh
          name="Cone047"
          castShadow
          receiveShadow
          geometry={nodes.Cone047.geometry}
          material={materials['Material.052']}
          position={[1.969, 0.351, -0.597]}
          rotation={[-3.136, 0.017, 3.068]}
          scale={[0.087, 0.116, 0.087]}
        />
        <mesh
          name="Cone048"
          castShadow
          receiveShadow
          geometry={nodes.Cone048.geometry}
          material={materials['Material.053']}
          position={[2.075, 0.417, -0.476]}
          rotation={[-0.04, 0.108, 0.027]}
          scale={[0.056, 0.075, 0.056]}
        />
        <mesh
          name="Cone049"
          castShadow
          receiveShadow
          geometry={nodes.Cone049.geometry}
          material={materials['Material.054']}
          position={[1.704, 0.354, -1.124]}
          rotation={[-0.808, 1.451, 0.773]}
          scale={[0.07, 0.092, 0.07]}
        />
        <mesh
          name="Cone050"
          castShadow
          receiveShadow
          geometry={nodes.Cone050.geometry}
          material={materials['Material.055']}
          position={[1.829, 0.276, -1.004]}
          rotation={[0.005, 1.102, -0.013]}
          scale={[0.13, 0.172, 0.13]}
        />
        <mesh
          name="Cone051"
          castShadow
          receiveShadow
          geometry={nodes.Cone051.geometry}
          material={materials['Material.056']}
          position={[1.865, 0.319, -0.787]}
          rotation={[-0.276, 1.489, 0.263]}
          scale={[0.101, 0.134, 0.101]}
        />
        <mesh
          name="Cone052"
          castShadow
          receiveShadow
          geometry={nodes.Cone052.geometry}
          material={materials['Material.057']}
          position={[1.721, 0.385, -1.232]}
          rotation={[0.584, -1.505, 0.614]}
          scale={[0.078, 0.104, 0.078]}
        />
        <mesh
          name="Cone053"
          castShadow
          receiveShadow
          geometry={nodes.Cone053.geometry}
          material={materials['Material.058']}
          position={[0.071, -0.046, 4.336]}
          rotation={[-0.022, -0.155, -0.015]}
          scale={[0.189, 0.251, 0.189]}
        />
        <mesh
          name="Cone054"
          castShadow
          receiveShadow
          geometry={nodes.Cone054.geometry}
          material={materials['Material.059']}
          position={[0.744, 0.059, 4.14]}
          rotation={[-0.022, -0.155, -0.015]}
          scale={[0.135, 0.18, 0.135]}
        />
        <mesh
          name="Cone055"
          castShadow
          receiveShadow
          geometry={nodes.Cone055.geometry}
          material={materials['Material.059']}
          position={[0.587, 0.084, 4.37]}
          rotation={[-0.045, 0.234, -0.013]}
          scale={[0.098, 0.13, 0.098]}
        />
        <mesh
          name="Cone056"
          castShadow
          receiveShadow
          geometry={nodes.Cone056.geometry}
          material={materials['Material.060']}
          position={[1.566, -0.003, 4.039]}
          rotation={[-0.42, 1.466, 0.427]}
          scale={[0.144, 0.191, 0.144]}
        />
        <mesh
          name="Cone057"
          castShadow
          receiveShadow
          geometry={nodes.Cone057.geometry}
          material={materials['Material.061']}
          position={[1.883, 0.098, 3.815]}
          rotation={[-0.076, 1.463, 0.075]}
          scale={[0.094, 0.125, 0.094]}
        />
        <mesh
          name="Cone058"
          castShadow
          receiveShadow
          geometry={nodes.Cone058.geometry}
          material={materials['Material.061']}
          position={[2.083, 0.005, 3.735]}
          rotation={[-3.114, 1.283, 3.095]}
          scale={[0.111, 0.148, 0.111]}
        />
        <mesh
          name="Cone059"
          castShadow
          receiveShadow
          geometry={nodes.Cone059.geometry}
          material={materials['Material.062']}
          position={[1.208, 0.08, 4.103]}
          rotation={[-3.114, 1.283, 3.095]}
          scale={[0.079, 0.104, 0.079]}
        />
        <mesh
          name="Cone060"
          castShadow
          receiveShadow
          geometry={nodes.Cone060.geometry}
          material={materials['Material.062']}
          position={[1.065, 0.006, 4.423]}
          rotation={[-0.076, 1.463, 0.075]}
          scale={[0.099, 0.131, 0.099]}
        />
        <mesh
          name="Cone061"
          castShadow
          receiveShadow
          geometry={nodes.Cone061.geometry}
          material={materials['Material.063']}
          position={[-1.012, 0.315, -2.032]}
          rotation={[-3.067, 1.258, 3.066]}
          scale={[0.109, 0.145, 0.109]}
        />
        <mesh
          name="Cone062"
          castShadow
          receiveShadow
          geometry={nodes.Cone062.geometry}
          material={materials['Material.064']}
          position={[-0.913, 0.213, -2.521]}
          rotation={[-0.346, 1.432, 0.272]}
          scale={[0.128, 0.169, 0.128]}
        />
        <mesh
          name="Cone063"
          castShadow
          receiveShadow
          geometry={nodes.Cone063.geometry}
          material={materials['Material.065']}
          position={[-0.917, 0.223, -3.005]}
          rotation={[-2.972, 1.274, 2.936]}
          scale={[0.07, 0.093, 0.07]}
        />
        <mesh
          name="Circle003"

          receiveShadow
          geometry={nodes.Circle003.geometry}
          material={materials['Material.066']}
          position={[0, 0.006, 0]}
          scale={[3.9, 4.682, 3.9]}
        />
        <mesh
          name="Cone064"
          castShadow
          receiveShadow
          geometry={nodes.Cone064.geometry}
          material={materials['Material.067']}
          position={[4.065, 0.134, 1.627]}
          rotation={[-1.317, 1.437, 1.347]}
          scale={[0.07, 0.093, 0.07]}
        />
        <mesh
          name="Cone065"
          castShadow
          receiveShadow
          geometry={nodes.Cone065.geometry}
          material={materials['Material.068']}
          position={[3.693, 0.096, 2.118]}
          rotation={[-0.162, 1.118, 0.166]}
          scale={[0.128, 0.169, 0.128]}
        />
        <mesh
          name="Cone066"
          castShadow
          receiveShadow
          geometry={nodes.Cone066.geometry}
          material={materials['Material.069']}
          position={[3.449, 0.088, 2.554]}
          rotation={[-1.413, 1.528, 1.402]}
          scale={[0.109, 0.145, 0.109]}
        />
        <mesh
          name="Cone067"
          castShadow
          receiveShadow
          geometry={nodes.Cone067.geometry}
          material={materials['Material.070']}
          position={[3.894, 0.083, 1.737]}
          rotation={[-3.009, 1.272, 3.026]}
          scale={[0.132, 0.175, 0.132]}
        />
        <mesh
          name="Cone068"
          castShadow
          receiveShadow
          geometry={nodes.Cone068.geometry}
          material={materials['Material.071']}
          position={[4.169, 0.086, 1.734]}
          rotation={[-3.009, 1.272, 3.026]}
          scale={[0.088, 0.116, 0.088]}
        />
        <mesh
          name="Cone069"
          castShadow
          receiveShadow
          geometry={nodes.Cone069.geometry}
          material={materials['Material.072']}
          position={[3.799, 0.124, 1.959]}
          rotation={[-3.006, 1.277, 3.027]}
          scale={[0.091, 0.121, 0.091]}
        />
        <group
          name="Sketchfab_model003"
          position={[4.407, 0.342, -0.955]}
          rotation={[-1.725, -0.06, -1.995]}
          scale={0.359}>
          <group name="Collada_visual_scene_group001" rotation={[Math.PI / 2, 0, 0]}>
            <group name="Cube003">
              <mesh
                name="defaultMaterial001"
                castShadow
                receiveShadow
                geometry={nodes.defaultMaterial001.geometry}
                material={materials['DefaultMaterial.002']}
                position={[-0.015, -0.09, 0.01]}
                rotation={[0.103, 0.91, -0.262]}
              />
            </group>
          </group>
        </group>
        <mesh
          name="Cone070"
          castShadow
          receiveShadow
          geometry={nodes.Cone070.geometry}
          material={materials['Material.073']}
          position={[-2.371, 0.04, -3.841]}
          rotation={[-3.006, 1.277, 3.027]}
          scale={[0.091, 0.121, 0.091]}
        />
        <mesh
          name="Cone071"
          castShadow
          receiveShadow
          geometry={nodes.Cone071.geometry}
          material={materials['Material.074']}
          position={[-2.587, 0.078, -3.366]}
          rotation={[-1.413, 1.528, 1.402]}
          scale={[0.109, 0.145, 0.109]}
        />
        <mesh
          name="Cone072"
          castShadow
          receiveShadow
          geometry={nodes.Cone072.geometry}
          material={materials['Material.075']}
          position={[-2.478, 0.012, -3.682]}
          rotation={[-0.162, 1.118, 0.166]}
          scale={[0.128, 0.169, 0.128]}
        />
        <mesh
          name="Cone073"
          castShadow
          receiveShadow
          geometry={nodes.Cone073.geometry}
          material={materials['Material.076']}
          position={[-3.14, 0.329, -1.434]}
          rotation={[-0.076, 1.463, 0.075]}
          scale={[0.099, 0.131, 0.099]}
        />
        <mesh
          name="Cone074"
          castShadow
          receiveShadow
          geometry={nodes.Cone074.geometry}
          material={materials['Material.077']}
          position={[-2.988, 0.068, -3.187]}
          rotation={[-0.045, 0.234, -0.013]}
          scale={[0.098, 0.13, 0.098]}
        />
        <mesh
          name="Cone075"
          castShadow
          receiveShadow
          geometry={nodes.Cone075.geometry}
          material={materials['Material.077']}
          position={[-2.759, 0.043, -3.104]}
          rotation={[-0.022, -0.155, -0.015]}
          scale={[0.135, 0.18, 0.135]}
        />
        <mesh
          name="Cone076"
          castShadow
          receiveShadow
          geometry={nodes.Cone076.geometry}
          material={materials['Material.078']}
          position={[-3.143, -0.047, -2.86]}
          rotation={[-0.022, -0.155, -0.015]}
          scale={[0.189, 0.251, 0.189]}
        />
      </group>
    </a.group>
  )
}

export default Island;




